---
title: "Infovis Abgabe"
author: "Leonie Düttmann, Laura Schröder"
date: "5 6 2019"
output: html_document
---

##College Abschlüsse in den USA und das Phänomen "Gender Pay Gap"
Hier Erklärtext zum Problem.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("gridExtra")
library(tidyverse)
library(lubridate)
library(ggplot2)
library(esquisse)
library(gridExtra)
library(here)

#install.packages("devtools")
#devtools::install_github("thomasp85/patchwork")
```


```{r message=FALSE, warning=FALSE, paged.print=FALSE}
jobs_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/jobs_gender.csv")
earnings_female <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/earnings_female.csv") 
employed_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/employed_gender.csv") 



college_major <- readr::read_csv("recent-grads.csv")

rwthcolors <- hcictools::rwth.colorpalette()

```

```{r Diagramme I College Major nach Kategorie und Geschlecht; female und male workers nach major category}

college_major %>% select(Men, Women, Major_category, Major) %>% 
  gather(gender, value, -Major_category, -Major) %>% 
  group_by(Major_category, gender) %>% 
  summarize(subtotal = sum(value)) %>%
  ungroup() %>% 
  mutate(Major_category = fct_reorder(Major_category, subtotal)) %>% 
  ggplot() +
  aes(x = Major_category, y = subtotal, fill = gender) + geom_col() + coord_flip() +
  scale_fill_manual(values = c(rwthcolors$blue, rwthcolors$red)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) 
  
  
  
  


jobs_gender %>% select(major_category, minor_category, workers_male, workers_female) %>% 
  gather(gender, value, -major_category, -minor_category) %>% 
  group_by(major_category, gender) %>% 
  summarize(subtotal = sum(value)) %>% 
  ungroup() %>% 
  mutate(major_category = fct_reorder(major_category, subtotal)) %>% 
  ggplot() +
  aes(x = major_category, y = subtotal, fill = gender) + geom_col(position = "dodge") + coord_flip() +
  scale_fill_manual(values = c(rwthcolors$red, rwthcolors$blue)) +
 scale_y_continuous(labels = scales::percent_format(accuracy = 1)) 
  


```

## Anteil weiblicher und männlicher Arbeiter nach Abschlusskategorie
Hier kommt das erste Zwischenfazit.

```{r full-time und part-time Vergleich}

total_work <- list (WORK = c("full_time_female", "full_time_male", "part_time_female", "part_time_male"))


employed_gender %>% 
  filter(year == 2013) %>% 
  select(-starts_with("total")) %>% 
  gather(variable, value, -year) %>%
  mutate(gender = case_when(
    str_detect(variable, "female") ~ "female",
    str_detect(variable, "male") ~ "male"),
    type_of_work = case_when(
    str_detect(variable, "part") ~ "part time",
    str_detect(variable, "full") ~ "full time")) %>%  
  mutate(value = value / 100) %>% 
  ggplot() +
  aes(x = gender, y = value, fill = type_of_work) + 
  geom_bar(stat = "identity") +
  theme_minimal() +
  scale_fill_manual(values = c(rwthcolors$turquois, rwthcolors$orange)) 



```


```{r}
library(ggplot2)

ggplot(data = jobs_gender) +
  aes(x = major_category, weight = year) +
  geom_bar(fill = '#0c4c8a') +
  theme_minimal() + 
  coord_flip()


ggplot(data = jobs_gender) +
  aes(x = major_category, fill = workers_female, weight = year) +
  geom_bar() +
  theme_minimal()+
  coord_flip()

ggplot(data = jobs_gender) +
  aes(x = major_category, fill = workers_male, weight = year) +
  geom_bar() +
  theme_minimal() + 
  coord_flip()

  
```


```{r Vergleich Gehalt Männer und Frauen}


jobs_gender %>% 
  filter(year == 2013, major_category != "Healthcare Practitioners and Technical") %>%
  select(major_category, total_earnings_male) %>% 
  group_by(major_category) %>% 
  summarise(total = mean(total_earnings_male)) %>% 
  ggplot() +
  aes(x = major_category, y = total) +
  geom_bar(stat = "identity") +
  coord_flip() 

  jobs_gender %>% 
  filter(year == 2013, major_category != "Healthcare Practitioners and Technical") %>%
  select(major_category, total_earnings_female) %>% 
  group_by(major_category) %>% 
  summarise(total = mean(total_earnings_female)) %>% 
  ggplot() +
  aes(x = major_category, y = total) +
  geom_bar(stat = "identity") +
  coord_flip() 


 
```

